metal:
  children:
    masters:
      hosts:
        metal2: {ansible_host: 192.168.88.102, vip: 192.168.88.100, mac: '00:23:24:d1:da:d8', disk: sda, network_interface: eno1}
        metal3: {ansible_host: 192.168.88.103, vip: 192.168.88.100, mac: '00:23:24:af:e2:a0', disk: sda, network_interface: eno1}
        metal4: {ansible_host: 192.168.88.104, vip: 192.168.88.100, mac: '00:23:24:c0:1e:67', disk: sda, network_interface: eno1}
    workers:
      hosts: 
        metal5: {ansible_host: 192.168.88.105, mac: '00:23:24:c7:61:e7', disk: sda, network_interface: eno1}
        metal6: {ansible_host: 192.168.88.106, mac: '00:23:24:ae:f7:28', disk: sda, network_interface: eno1}

