gitea:
  ingress:
    enabled: true
    className: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      nginx.ingress.kubernetes.io/proxy-body-size: 0m
    hosts:
      - host: &host git.jopo.dev
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: gitea-tls-certificate
        hosts:
          - *host
  gitea:
    admin:
      existingSecret: gitea-admin-secret
    config:
      server:
        LANDING_PAGE: explore
        ROOT_URL: https://git.jopo.dev
      webhook:
        ALLOWED_HOST_LIST: "*.jopo.dev,*.slack.com"
      Time:
        DEFAULT_UI_LOCATION: Europe/Warsaw
      repository:
        ENABLE_PUSH_CREATE_USER: true
        upload:
          FILE_MAX_SIZE: 10
          MAX_FILES: 10
      indexer:
        REPO_INDEXER_ENABLED: true
  persistence:
    storageClass: longhorn
    mount: true
    create: false
    claimName: data-gitea-0
  postgresql:
    enabled: true
    persistence:
      storageClass: longhorn
  postgresql-ha:
    enabled: false
