users:
  - name: renovate
    tokenSecretRef: renovate-secret # ???
organizations:
  - name: ops
    members:
      - renovate
repositories:
  - path: ops/homelab
    migrate:
      source: https://github.com/jonatanpolak/homelab
      mirror: false
    webhooks:
      - http://gitea-webhook.tekton-pipelines:3000
  # - path: zanelab/blog
  #   webhooks:
  #     - http://gitea-webhook.tekton-pipelines:3000
  # - path: zanelab/backstage
  #   webhooks:
  #     - http://gitea-webhook.tekton-pipelines:3000
